version: '2'

networks:
  nursa-local-network:
    driver: bridge
    name: nursa-local-network

x-resources: &resources
  deploy:
    resources:
      limits:
        cpus: "0.2"
        memory: 200M

services:
  rabbitmq1:
    networks:
      - nursa-local-network
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "8080:15672"
      - "9080:5672"
    volumes:
     - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=true
    <<: [*resources]

  rabbitmq2:
    networks:
      - nursa-local-network
    image: rabbitmq:3-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    ports:
      - "8081:5672"
      - "9081:15672"
    volumes:
     - $PWD/storage/rabbitmq2:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=true
    links:
     - rabbitmq1:rabbitmq1
    <<: [*resources]

  rabbitmq3:
    networks:
      - nursa-local-network
    image: rabbitmq:3-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    ports:
      - "8082:5672"
      - "9082:15672"
    volumes:
      - $PWD/storage/rabbitmq3:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=true
    links:
     - rabbitmq1:rabbitmq1
     - rabbitmq2:rabbitmq2
    <<: [*resources]

  rabbitmq4:
    networks:
      - nursa-local-network
    image: rabbitmq:3-management
    container_name: rabbitmq4
    hostname: rabbitmq4
    ports:
      - "8083:5672"
      - "9083:15672"
    volumes:
      - $PWD/storage/rabbitmq4:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=true
    links:
     - rabbitmq1:rabbitmq1
     - rabbitmq2:rabbitmq2
     - rabbitmq3:rabbitmq3
    <<: [*resources]

  rabbitmq:
    networks:
        - nursa-local-network
    image: haproxy:rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbtimq-haproxy
    hostname: rabbtimq-haproxy
    ports:
      - 5672:5672
      - 20000:20000 #ha-proxy admin
      - 15672:15672 #rabbitmq-admin
    links:
      - rabbitmq1:rabbitmq1
      - rabbitmq2:rabbitmq2
      - rabbitmq3:rabbitmq3
      - rabbitmq4:rabbitmq4
    <<: [*resources]